# Generated by Django 4.2.11 on 2024-05-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_moviereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True),
        ),
    ]
